apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-first-declarative-deployment
spec:
  paused: false
  selector:
    matchLabels:
      app: my-first-declarative
    spec:
      containers:
      - name: go-hello-world
        image: dockercampusmvp/go-hello-world
        imagePullPolicy: Always
